{
  "openapi": "3.1.0",
  "info": {
    "title": "Blog Application",
    "contact": {},
    "version": "1.0"
  },
  "jsonSchemaDialect": "https://json-schema.org/draft/2020-12/schema",
  "servers": [
    {
      "url": "http://example.com/api/v1",
      "variables": {}
    }
  ],
  "paths": {
    "/articles": {
      "get": {
        "tags": [
          "Articles"
        ],
        "summary": "Get all the Articles",
        "description": "## Get all data from database",
        "operationId": "GetalltheArticles",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "post": {
        "tags": [
          "Articles"
        ],
        "summary": "Create new Article",
        "operationId": "CreatenewArticle",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreatenewArticleRequest"
              },
              "example": {
                "name": "Test Article part V",
                "duration": 1,
                "maxGroupSize": 1,
                "difficulty": "easy",
                "ratingsAverage": 4.2,
                "ratingsQuantity": 10,
                "price": 1270,
                "summary": "Breathtaking hike through the Canadian Banff National Park",
                "description": "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.\nLorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                "imageCover": "article-1-cover.jpg",
                "images": [
                  "article-1-1.jpg",
                  "article-1-2.jpg",
                  "article-1-3.jpg"
                ],
                "startDates": [
                  "2021-04-25,10:00",
                  "2021-07-20,10:00",
                  "2021-10-05,10:00"
                ]
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/articles/6192f3db412d6810b6bfe002": {
      "get": {
        "tags": [
          "Articles"
        ],
        "summary": "Get single Article",
        "operationId": "GetsingleArticle",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "patch": {
        "tags": [
          "Articles"
        ],
        "summary": "Update Article",
        "operationId": "UpdateArticle",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateArticleRequest"
              },
              "example": {
                "name": "Test Article I"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/articles/6192feedd1904ba85e17c41d": {
      "delete": {
        "tags": [
          "Articles"
        ],
        "summary": "Delete Article",
        "operationId": "DeleteArticle",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/comments": {
      "get": {
        "tags": [
          "Comments"
        ],
        "summary": "Get All Comments",
        "operationId": "GetAllComments",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "post": {
        "tags": [
          "Comments"
        ],
        "summary": "Create Comment",
        "operationId": "CreateComment",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateCommentRequest"
              },
              "example": {
                "comment": "AWESOME",
                "rating": 5,
                "article": "6192f3db412d6810b6bfe002",
                "user": "6192f7f7d1904ba85e17c3b7"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/comments/6192f81cd1904ba85e17c3bd": {
      "get": {
        "tags": [
          "Comments"
        ],
        "summary": "Get Single Comment",
        "operationId": "GetSingleComment",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "patch": {
        "tags": [
          "Comments"
        ],
        "summary": "Update Comment",
        "operationId": "UpdateComment",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateCommentRequest"
              },
              "example": {
                "rating": 5
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "delete": {
        "tags": [
          "Comments"
        ],
        "summary": "Delete Comment",
        "operationId": "DeleteComment",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/articles/6192f3db412d6810b6bfe002/comments": {
      "get": {
        "tags": [
          "Comments"
        ],
        "summary": "Get All Reviews on Tour",
        "operationId": "GetAllReviewsonTour",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "post": {
        "tags": [
          "Comments"
        ],
        "summary": "Create New Review on Tour",
        "operationId": "CreateNewReviewonTour",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateNewReviewonTourRequest"
              },
              "example": {
                "rating": 4,
                "comment": "It's Amazing"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/users": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Get All Users",
        "description": "## Get all data from database",
        "operationId": "GetAllUsers",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/users/6192f7f7d1904ba85e17c3b7": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Get single User",
        "operationId": "GetsingleUser",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "patch": {
        "tags": [
          "Users"
        ],
        "summary": "Update User",
        "operationId": "UpdateUser",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateUserRequest"
              },
              "example": {
                "name": "User Satu"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/users/618706fc14357fd1a675ccca": {
      "delete": {
        "tags": [
          "Users"
        ],
        "summary": "Delete user",
        "operationId": "Deleteuser",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/users/me": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Get Current User",
        "operationId": "GetCurrentUser",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/users/updateMe": {
      "patch": {
        "tags": [
          "Users"
        ],
        "summary": "Update Current User Data (User)",
        "operationId": "UpdateCurrentUserData(User)",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateCurrentUserDataUserRequest"
              },
              "example": {
                "name": "rianto",
                "role": "admin"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/users/deleteMe": {
      "delete": {
        "tags": [
          "Users"
        ],
        "summary": "Delete Current User (User)",
        "operationId": "DeleteCurrentUser(User)",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DeleteCurrentUserUserRequest"
              },
              "example": {
                "name": "Rianto",
                "role": "user"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/users/signup": {
      "post": {
        "tags": [
          "Authentications"
        ],
        "summary": "Sign Up",
        "operationId": "SignUp",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SignUpRequest"
              },
              "example": {
                "name": "User IV",
                "email": "four@user.com",
                "password": "12345678",
                "passwordConfirm": "12345678"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/users/login": {
      "post": {
        "tags": [
          "Authentications"
        ],
        "summary": "Login",
        "operationId": "Login",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              },
              "example": {
                "email": "rian@gmail.com",
                "password": "12345678"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    }
  },
  "components": {
    "schemas": {
      "CreatenewArticleRequest": {
        "title": "CreatenewArticleRequest",
        "required": [
          "name",
          "duration",
          "maxGroupSize",
          "difficulty",
          "ratingsAverage",
          "ratingsQuantity",
          "price",
          "summary",
          "description",
          "imageCover",
          "images",
          "startDates"
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "duration": {
            "type": "integer",
            "contentEncoding": "int32"
          },
          "maxGroupSize": {
            "type": "integer",
            "contentEncoding": "int32"
          },
          "difficulty": {
            "type": "string"
          },
          "ratingsAverage": {
            "type": "number"
          },
          "ratingsQuantity": {
            "type": "integer",
            "contentEncoding": "int32"
          },
          "price": {
            "type": "integer",
            "contentEncoding": "int32"
          },
          "summary": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "imageCover": {
            "type": "string"
          },
          "images": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": ""
          },
          "startDates": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": ""
          }
        },
        "examples": [
          {
            "name": "Test Article part V",
            "duration": 1,
            "maxGroupSize": 1,
            "difficulty": "easy",
            "ratingsAverage": 4.2,
            "ratingsQuantity": 10,
            "price": 1270,
            "summary": "Breathtaking hike through the Canadian Banff National Park",
            "description": "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.\nLorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            "imageCover": "article-1-cover.jpg",
            "images": [
              "article-1-1.jpg",
              "article-1-2.jpg",
              "article-1-3.jpg"
            ],
            "startDates": [
              "2021-04-25,10:00",
              "2021-07-20,10:00",
              "2021-10-05,10:00"
            ]
          }
        ]
      },
      "UpdateArticleRequest": {
        "title": "UpdateArticleRequest",
        "required": [
          "name"
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          }
        },
        "examples": [
          {
            "name": "Test Article I"
          }
        ]
      },
      "CreateCommentRequest": {
        "title": "CreateCommentRequest",
        "required": [
          "comment",
          "rating",
          "article",
          "user"
        ],
        "type": "object",
        "properties": {
          "comment": {
            "type": "string"
          },
          "rating": {
            "type": "integer",
            "contentEncoding": "int32"
          },
          "article": {
            "type": "string"
          },
          "user": {
            "type": "string"
          }
        },
        "examples": [
          {
            "comment": "AWESOME",
            "rating": 5,
            "article": "6192f3db412d6810b6bfe002",
            "user": "6192f7f7d1904ba85e17c3b7"
          }
        ]
      },
      "UpdateCommentRequest": {
        "title": "UpdateCommentRequest",
        "required": [
          "rating"
        ],
        "type": "object",
        "properties": {
          "rating": {
            "type": "integer",
            "contentEncoding": "int32"
          }
        },
        "examples": [
          {
            "rating": 5
          }
        ]
      },
      "CreateNewReviewonTourRequest": {
        "title": "CreateNewReviewonTourRequest",
        "required": [
          "rating",
          "comment"
        ],
        "type": "object",
        "properties": {
          "rating": {
            "type": "integer",
            "contentEncoding": "int32"
          },
          "comment": {
            "type": "string"
          }
        },
        "examples": [
          {
            "rating": 4,
            "comment": "It's Amazing"
          }
        ]
      },
      "UpdateUserRequest": {
        "title": "UpdateUserRequest",
        "required": [
          "name"
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          }
        },
        "examples": [
          {
            "name": "User Satu"
          }
        ]
      },
      "UpdateCurrentUserDataUserRequest": {
        "title": "UpdateCurrentUserDataUserRequest",
        "required": [
          "name",
          "role"
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "role": {
            "type": "string"
          }
        },
        "examples": [
          {
            "name": "rianto",
            "role": "admin"
          }
        ]
      },
      "DeleteCurrentUserUserRequest": {
        "title": "DeleteCurrentUserUserRequest",
        "required": [
          "name",
          "role"
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "role": {
            "type": "string"
          }
        },
        "examples": [
          {
            "name": "Rianto",
            "role": "user"
          }
        ]
      },
      "SignUpRequest": {
        "title": "SignUpRequest",
        "required": [
          "name",
          "email",
          "password",
          "passwordConfirm"
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "passwordConfirm": {
            "type": "string"
          }
        },
        "examples": [
          {
            "name": "User IV",
            "email": "four@user.com",
            "password": "12345678",
            "passwordConfirm": "12345678"
          }
        ]
      },
      "LoginRequest": {
        "title": "LoginRequest",
        "required": [
          "email",
          "password"
        ],
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "examples": [
          {
            "email": "rian@gmail.com",
            "password": "12345678"
          }
        ]
      }
    },
    "securitySchemes": {
      "httpBearer": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "security": [
    {
      "httpBearer": []
    }
  ],
  "tags": [
    {
      "name": "Articles"
    },
    {
      "name": "Comments"
    },
    {
      "name": "Users"
    },
    {
      "name": "Authentications"
    }
  ]
}